sudo: required
services: # services that we need pre-installed as soon as we run our build
  - docker
before_install:
  # For encrypted service-account.json file
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d 
  # Download and Intsall Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl
  - gcloud components update kubectl
  # Login to Google Cloud CLI (service-account.json contains the credentials)
  - gcloud auth activate-service-account --key-file service-account.json
