sudo: required

services: # services that we need pre-installed as soon as we run our build
  - docker

env: # environment variables
  global:
    - SHA=$(git rev-parse HEAD) # SHA is the commit hash of the commit that we are trying to deploy
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # to disable any prompts that Google Cloud SDK might show us

before_install: # Setups for our project
  # For converting the encrypted service-account.json.enc file, to decrypted service-account.json
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d 
  # Download and Intsall Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl
  - gcloud components update kubectl
  # Login to Google Cloud CLI (service-account.json contains the credentials)
  - gcloud auth activate-service-account --key-file service-account.json
  # Set the project to the one we created in Google Cloud
  - gcloud config set project multi-k8s-386101
  # Set the compute zone to the one we created in Google Cloud
  - gcloud config set compute/zone us-central1-c
  # Set the cluster to the one we created in Google Cloud for any further k8s commands
  - gcloud container clusters get-credentials multi-cluster
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build the test version of multi-client
  - docker build -t mananparuthi/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run the test version of multi-client
  - docker run -e CI=true mananparuthi/react-test npm test

deploy: # we are telling Travis CI to run a script to deploy our application instead of deploying our application to any provider
  provider: script 
  script: bash ./deploy.sh # deploy.sh is a script that we will write to deploy our application
  on: # we are telling Travis CI to run the deploy script only when we push code to the master branch
    branch: master